# Question:
### What percent of mushrooms in this dataset are poisonous?

## Type of study:
### Census -- I will look at all the mushrooms in the dataset and determine which are poisonous and then determine the percentage of the poisinous mushrooms out of the whole dataset

In [39]:
import pandas as pd
from IPython.display import Markdown, display

In [27]:
fungi_data = pd.read_csv("mushrooms.csv")

In [28]:
fungi_data.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [29]:
fungi_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   str
 1   cap-shape                 8124 non-null   str
 2   cap-surface               8124 non-null   str
 3   cap-color                 8124 non-null   str
 4   bruises                   8124 non-null   str
 5   odor                      8124 non-null   str
 6   gill-attachment           8124 non-null   str
 7   gill-spacing              8124 non-null   str
 8   gill-size                 8124 non-null   str
 9   gill-color                8124 non-null   str
 10  stalk-shape               8124 non-null   str
 11  stalk-root                8124 non-null   str
 12  stalk-surface-above-ring  8124 non-null   str
 13  stalk-surface-below-ring  8124 non-null   str
 14  stalk-color-above-ring    8124 non-null   str
 15  stalk-color-below-ring    8124 non-null   str
 16  veil-type                 8124 non-null   str
 17  veil-color                8124 non-null   str
 18  ring-number               8124 non-null   str
 19  ring-type                 8124 non-null   str
 20  spore-print-color         8124 non-null   str
 21  population                8124 non-null   str
 22  habitat                   8124 non-null   str
dtypes: str(23)
memory usage: 1.6 MB

In [30]:
fungi_data["class"].describe()

count     8124
unique       2
top          e
freq      4208
Name: class, dtype: object

In [31]:
fungi_data["class"].value_counts()

class
e    4208
p    3916
Name: count, dtype: int64

In [32]:
survived = fungi_data[fungi_data["class"] == "p"]

In [33]:
survived.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
13,p,x,y,w,t,p,f,c,n,k,...,s,w,w,p,w,o,p,n,v,u
17,p,x,s,n,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,g

In [34]:
survived.info()

<class 'pandas.DataFrame'>
Index: 3916 entries, 0 to 8122
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     3916 non-null   str
 1   cap-shape                 3916 non-null   str
 2   cap-surface               3916 non-null   str
 3   cap-color                 3916 non-null   str
 4   bruises                   3916 non-null   str
 5   odor                      3916 non-null   str
 6   gill-attachment           3916 non-null   str
 7   gill-spacing              3916 non-null   str
 8   gill-size                 3916 non-null   str
 9   gill-color                3916 non-null   str
 10  stalk-shape               3916 non-null   str
 11  stalk-root                3916 non-null   str
 12  stalk-surface-above-ring  3916 non-null   str
 13  stalk-surface-below-ring  3916 non-null   str
 14  stalk-color-above-ring    3916 non-null   str
 15  stalk-color-below-ring    3916 non-null   str
 16  veil-type                 3916 non-null   str
 17  veil-color                3916 non-null   str
 18  ring-number               3916 non-null   str
 19  ring-type                 3916 non-null   str
 20  spore-print-color         3916 non-null   str
 21  population                3916 non-null   str
 22  habitat                   3916 non-null   str
dtypes: str(23)
memory usage: 833.2 KB

In [35]:
poison_number = survived.shape[0]

In [36]:
total_number = fungi_data.shape[0]

In [37]:
rf_of_class = poison_number / total_number * 100

In [44]:
display(Markdown("# Conclustion"))
display(Markdown(f"### The amount of poison mushrooms in this dataset is {round(rf_of_class, 3)}%"))

# Conclustion

### The amount of poison mushrooms in this dataset is 48.203%